---
- name: Operating system dependencies
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev
    - git
    - python-virtualenv
    - dialog
    - libaugeas0
    - ca-certificates
- name: Python cryptography module
  pip: name=cryptography
- name: Letsencrypt Python client
  git:
    dest: /opt/certbot
    clone: yes
    update: yes
    repo: https://github.com/certbot/certbot
    force: yes
    version: '{{letsencrypt_certbot_version}}'
